cadena1 ="uriel santarelli"
cadena2 ="Bienvenido"
cadena3="GANAR"

print(cadena2.find("e"))

#DIR: DEVUELVE LA LISTA DE ATRIBUTOS VALIDOS DEL OBJETO PASADO

#UPPER: CONVIERTE A MAYUSCULA

#LOWER: CONVIERTE A MINUSCULA

#CAPITALIZE: PRIMERA EN MAYUSCULA

#FIND: METODO QUE ENCUENTRA LA PRIMERA APARICION DEL VALOR ESPECIFICADO, SI DICHO VALOR NO EXISTE NOS DEVUELVE -1

#INDEX: METODO QUE ENCUENTRA LA PRIMERA APARICION DEL VALOR ESPECIFICADO, SINO QUE DEVUELVE UNA EXCEPCION/ERROR

#ISNUMERIC: SI ES NUMERICO DEVUELVE TRUE

#ISALPHA: SI ES ALFA-NUMERICO DEVUELVE TRUE

#COUNT: DEVUELVE DEVUELVE EL NUMERO DE OCURRENCIAS DE UNA SUBCADENA EN LA CADENA DADA

#LEN: CUENTA LOS CARACTERES DE UNA CADENA

#ENDSWITH: VERIFICA SI UNA CADENA COMIENZA CON

#STARTSWITH: VERIFICA SI UAN CADENA TERMINA CON

#REPLACE: REEMPLAZA UN VALOR POR OTRO

#SPLIT: SEPARA EL PARAMETRO DADO