# SUMA Y RESTA
SUMA= 12+5
RESTA=10-5

#MULTIPLICACION Y DIVISION
MULTI=12*3
DIV=15/5 #DEVUELVE DATO FLOAT (FLOTANTE)

#POTENCIACION
EXPONENTE =12**5

#DIVIOSN BAJA
DIVISION_BAJA=12//5

#RESTO O MODULO
RESTO= 12%5

print(DIV)

#TYPE(DATO) DEVUELVE EL TIPO DE DATO
tipo_de_dato =type(SUMA)

print(tipo_de_dato)